### ISSUE TITLE
Circles are not round in svg import

### ISSUE THREAD

**Issue by defr0zen** [CarbonDesigns/carbon-ui#131]
Unpack and import svg. It should be round.

[adn.svg.zip](https://github.com/CarbonDesigns/carbon-ui/files/1192020/adn.svg.zip)

![image](https://user-images.githubusercontent.com/27830024/28848366-f4d6838e-7712-11e7-93e4-4688dbd4c71e.png)

**Comment by alex-carbonium** [comment]
fixed
