### ISSUE TITLE
[bug] Text label resizes frame improperly

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#153]
repro
---

- create text label
- insert >5 letters (like _werwerwer_)
- set central adjustment (not left which is by default)
- deselect this text input
- select again (double click)
- start typing, and... **text jumps out of the frame** until length of text becomes big enough

![2017-08-24_15-22-15](https://user-images.githubusercontent.com/2145313/29657019-8444bc78-88e0-11e7-94bd-608dd75bc787.gif)

**Comment by defr0zen** [comment]
@boorj do you have a repro in the new empty project? can't repro.
![aug-24-2017 17-10-22](https://user-images.githubusercontent.com/27830024/29673379-53570dc8-88ef-11e7-97c0-3cd24df6b0c9.gif)

**Comment by Boorj** [comment]
yes. the same in brand new project.

**Comment by Boorj** [comment]
#### New dose:
![2017-08-27_00-49-29](https://user-images.githubusercontent.com/2145313/29743734-ba35130e-8ac1-11e7-9ae2-e8c5e2b4bde5.gif)

**Comment by defr0zen** [comment]
Fixed by changing text mode to Block when font align is changed.

**Comment by Boorj** [comment]
I suppose it's not the best solution. That only could work as a temporary fix.
1. it's unexpected behavior (!).
2. Often you place a label with right adjustment, and align that (and maybe pin/anchor) to right side of container. But you don't want to change text mode.

![image](https://user-images.githubusercontent.com/2145313/29748072-c9b8027a-8b37-11e7-8287-ebd4899d5090.png)

**Comment by defr0zen** [comment]
You should use constraints for that, not text alignment. Generally, it does not make sense to have text alignment in Label mode - how can you align text if the frame always wraps the text?

**Comment by Boorj** [comment]
Label is a text block, which keeps font size according to text block size. The same function is in Adobe Photoshop, Illustrator and in many other tools. And there's always text adjustment option.
There could be many cases, when i want to have text adjustment for `"label"` element.

**Comment by defr0zen** [comment]
for example?

**Comment by Boorj** [comment]
Label is used when you want to stretch text block by resizing frame.
So all single/short word labels, which are aligned right, go to that case.

**Comment by Boorj** [comment]
Also, when something is switched without a notification - it's unexpected / unpredictable for novices.

**Comment by defr0zen** [comment]
@Boorj text is now growing according to text adjustment. Labels support adjustment as well, no more implicit switches to block mode.
