### ISSUE TITLE
[bug] Selection by mouse dragging improvements

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#157]
### bug
- select object
- hold shift
- select other objects by dragging (selection rectangle)
The first object is being deselected -- ??? Why?

### improvements
There's a nice feature in 3d max: 
If you hold `alt` while selecting by selection rectangle or clicks, it subtracts from selection. 
If you press `ctrl` it adds to selection.

![image](https://user-images.githubusercontent.com/2145313/29705578-e5e4bb72-89a8-11e7-9bfb-68dfd07f7171.png)

[from here - 3ds max, basics or selecting objects](https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/3DSMax/files/GUID-1962BD49-AAD7-43FA-871E-5C2742C047B8-htm.html)

Usually, in any graphic software, when you press `shift` and select with rectangle , you add not included objects AND exclude intersection. So it also could be done here.
But when you press `ctrl` - it should only ADD, and when `alt` - it should only reduce selection.

**Comment by Boorj** [comment]
also it needs to be fixed. 
you should subtract from selection by holding ANY key

**Comment by defr0zen** [comment]
Shift + click toggles selection.
When selecting with a frame (click and drag), ctrl adds, shift toggles, alt removes.
