### ISSUE TITLE
[bug] Repeater's gaps

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#168]
In this case `v spacing` is zero, but there's still **1px gap**:

![image](https://user-images.githubusercontent.com/2145313/29748598-f2745306-8b43-11e7-921a-945b0088cfd0.png)

![carbonium_-_iron_2017-08-27_16-13-29](https://user-images.githubusercontent.com/2145313/29748590-c58b22b6-8b43-11e7-8f30-09b2940fe1d1.png)

Maybe you could make **negative** gap? negative vspacing should be limited by cell height/

**Comment by defr0zen** [comment]
Some repro hints?

**Comment by Boorj** [comment]
Draw a line as a bottom element, create repeater.

![2017-08-31_15-07-00](https://user-images.githubusercontent.com/2145313/29913095-3dac67b0-8e5e-11e7-8028-29c3ca9287d5.gif)

**Comment by Boorj** [comment]
@defr0zen  Also, if top element is 1px line, top cell is cropped by 0.5px

**Comment by alex-carbonium** [comment]
fixed
