### ISSUE TITLE
[bug] cropped repeater cell sometimes appears (blinking)

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#180]
### repro
- create object
- make repeater
- stretch repeater for ×3.1 height of cell, when the bottom cell is barely seen
- manipulate with visible cells

Sometimes cropped cell appears.

![2017-09-02_11-05-36](https://user-images.githubusercontent.com/2145313/29992802-fc5442ac-8fce-11e7-899f-8e319728bf51.gif)

In this gif:
when i stretched repeater again to ×7.1 height, and manipulated with cells, bottom cell blinked _but not cought by gif screen capture_ 😢

**Comment by alex-carbonium** [comment]
fixed
