### ISSUE TITLE
[bug] Transparent objects selection

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#181]
Object with transparent fill could be selected only by dragging.
Don't know if it's bug or not, but it's somehow unexpected.
![2017-09-02_11-20-06](https://user-images.githubusercontent.com/2145313/29992892-d94d30e6-8fd0-11e7-996e-b052507eb4cd.gif)
(in this gif i'm clicking almost all time)

**Comment by alex-carbonium** [comment]
by design
