### ISSUE TITLE
[bug] resizing background object

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#182]
Don't know if it's a bug or intended, but when i resize background object it's being shortly brought to front.
It's inconvenient.
![2017-09-02_11-29-56](https://user-images.githubusercontent.com/2145313/29992940-1cccd140-8fd2-11e7-8d07-f65aa888da9f.gif)

**Comment by defr0zen** [comment]
Yes, we fixed dragging scenarios, resize is next.

**Comment by alex-carbonium** [comment]
fixed
