### ISSUE TITLE
[bug] [feature request?] show full xpath in isolation

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#188]
You should show full breadcrumbs path, when group is isolated.

#### Not isolated:
![image](https://user-images.githubusercontent.com/2145313/29993153-a564fa72-8fd8-11e7-8ec5-872663ef9db3.png)

#### Isolated
![image](https://user-images.githubusercontent.com/2145313/29993156-b54d6e6a-8fd8-11e7-80ed-83cdf807a7ce.png)

#### should be 
    artboard 5 > group 9 > text 8
or somehow else, but indicated, which group you're in.

**Comment by Boorj** [comment]
#### Adobe Illustrator example:
![image](https://user-images.githubusercontent.com/2145313/29993166-f44bbd42-8fd8-11e7-82f1-de3823ac86ab.png)
Each parent group is also clickable

**Comment by alex-carbonium** [comment]
fixed
