### ISSUE TITLE
[bug] Isolation bugs

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#189]
1. In isolation you can select objects from out of the group.
![2017-09-02_12-25-36](https://user-images.githubusercontent.com/2145313/29993195-3162f2ee-8fda-11e7-85b4-046d2a60a8f3.gif)
In this example only object in group is grey rectangle.

2. When only 1 object is left in group, that should be ungroupped. For example, you're in isolation mode, delete all objects except one, then exit group. That group should be ungroupped.

**Comment by alex-carbonium** [comment]
fixed, except p.2 - not sure that it should be like this
