### ISSUE TITLE
[bug] Artboard moving and resizing bugs

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#194]
1. when you resize artboard by top-left corner, it moves all contents. It's unexpected behavior.
2. When moving/resizing artboard (especially in Symbol mode), dark border rectangle is following white fill rectangle with 1-3 seconds latency.
![2017-09-02_14-44-22](https://user-images.githubusercontent.com/2145313/29993910-ca4d8d3a-8fed-11e7-80dd-e807099b0b8c.gif)

**Comment by alex-carbonium** [comment]
1. by design
2. known issues, will fix

**Comment by Boorj** [comment]
1. by design - i suppose it's not the best solution, often you need to fit artboard to content. What will be the pipeline for that?
2. so you could close this issue when it's fixed 🙈

**Comment by Boorj** [comment]
Please, let users resize artboard without moving content.
If i want to move artboard+content, i'd prefer to _move_ artboard. Not resize.

![2017-09-04_14-02-03](https://user-images.githubusercontent.com/2145313/30015145-bb0e5934-9179-11e7-918a-095c0a73aefa.gif)

@defr0zen , what do you think?

**Comment by defr0zen** [comment]
I think dropping content on the artboard of the *smaller* size on the *left* is not a common scenario. A far more common scenario should be to resize the artboard and see how nice and responsive your design is, or resize and maintain the right margin. So I'd do nothing about the content.

**Comment by Boorj** [comment]
usually we resize by right edge, not left.

**Comment by defr0zen** [comment]
Exactly, and usually constraints (by default) are set to left. So the case in the latest gif is indeed quite rare.
