### ISSUE TITLE
[bug] Artboard strange size

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#195]
Don't have exact repro, but on one page i have symbol artboard, and on another page i put that stencil (symbol) and it's cropped in very strange way
![2017-09-02_14-51-54](https://user-images.githubusercontent.com/2145313/29993938-79459e5e-8fee-11e7-8997-74172b816785.gif)

**Comment by defr0zen** [comment]
Let's open again when we have a repro
