### ISSUE TITLE
[bug] Selecting image inside frame doesn't work

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#196]
Strange, but seems that selecting image inside image frame is not working.

#### feature requests
- I would also appreciate functions "fit frame", "fill frame"  in `context menu` or `contextbar`. Also "wrap frame" (around inner image).
- there has to be resizing with `ctrl` mod button (or something else), which resizes content proportionally with frame resize. Bound resize.
- Would be nice to have image tiling inside image frame. For example, you drag/resize one image inside image frame, and there appears tiled layer behind inner image. And it resizes according to that original main image.

**Comment by alex-carbonium** [comment]
fixed

**Comment by Boorj** [comment]
Is it already placed on site? 1.0.1523 - still not working
