### ISSUE TITLE
[bug] commands affect original element instead of cloned copy

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#202]
When i copy element and press `Ctrl+B` — disabling bold font affects original image, not copy.
![2017-09-03_20-47-54](https://user-images.githubusercontent.com/2145313/30003709-f00b556c-90eb-11e7-931a-eabbe254faa6.gif)

**Comment by defr0zen** [comment]
Hard to repro. The selection has changed a lot, so now it's even harder to figure out...
