### ISSUE TITLE
[bug] Frame disappears after nudging

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#212]
### repro
- select objects
- nudge by keyboard (up down)
frame disappears

**Comment by defr0zen** [comment]
This is by design. When you use keyboard increments, most likely you are doing high-precision positioning. In this case, frame stroke and (especially) resize points are standing in the way.
Taken from Sketch and/or Adobe XD.

**Comment by defr0zen** [comment]
Btw, to get frame back, just move the mouse over the selection.
