### ISSUE TITLE
[bug] shadow doesn't scale according to zoom level

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#216]
![image](https://user-images.githubusercontent.com/2145313/30035782-d27fdcb0-91d7-11e7-8c2e-cb45c3def951.png)

**Comment by defr0zen** [comment]
any repro?
1 px red shadow:
![image](https://user-images.githubusercontent.com/27830024/30037555-2afc1ffa-91bc-11e7-8cae-9d06c08042a6.png)

**Comment by alex-carbonium** [comment]
yes, it is related to blure. Make shadow like this 
![image](https://user-images.githubusercontent.com/29034418/30038797-eb597c82-91c8-11e7-85cf-6966067a2f56.png)

**Comment by alex-carbonium** [comment]
fixed
