### ISSUE TITLE
repeater content got crazy after project reload

### ISSUE THREAD

**Issue by alex-carbonium** [CarbonDesigns/carbon-ui#244]
1. create symbols with image and text
2. add this symbol and repeat it to a grid 4x4
3. from image panel drag images to each symbol
4. resize repeater to 3x3 (with mouse)
5. Reload project

result content looks not like it was before
also sometimes images just dissapear even without reload

**Comment by defr0zen** [comment]
Fixed main issues. I think I saw another problem with disappearing image, but can't repro anymore.
