### ISSUE TITLE
[bug] sometimes symbol preview is not deleted

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#292]
![img_13102017_030741_0](https://user-images.githubusercontent.com/2145313/31516870-3088a1b6-afc4-11e7-90bd-505211fec7a0.png)
i have no repro for this

looks like it was frozen while dragging or something else
![img_13102017_030955_0](https://user-images.githubusercontent.com/2145313/31516873-344ab118-afc4-11e7-952e-2cc4442d0917.png)

**Comment by defr0zen** [comment]
impossible to repro, nothing to correlate with in the logs.
