### ISSUE TITLE
[feature request] Hotkeys

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#298]
- [ ] `=`, `-`, `num +`, `num -`  : zoom in, zoom out
- [ ] `shift+o` :  artboard tool - secondary shortcut (from illustrator)
- [ ] `M` : rectangle (Illustrator, InDesign)

### Upd 1
- [ ] `\` : line tool

### Upd 2
- [ ] `ctrl+shift+L / C / R` : justify text - left, center, right

---
_Btw, `shift+x` (swap colors) works not always._

**Comment by defr0zen** [comment]
@Boorj Just FYI, all shortcuts are now here:
https://github.com/CarbonDesigns/carbon-ui/blob/master/src/Hotkeys.ts

In the future this json file will be "editable" by the user right inside the product.

**Comment by Boorj** [comment]
@defr0zen @malapheev updated
