### ISSUE TITLE
[bug] Glitchy editing

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#307]
![2017-10-13_19-51-05](https://user-images.githubusercontent.com/2145313/31547011-ea2ead3c-b04f-11e7-8733-b4a9eed6db7b.gif)

---
---
---

![2017-10-13_19-27-12](https://user-images.githubusercontent.com/2145313/31547019-efbef45a-b04f-11e7-8fce-64371035c04b.gif)

**Comment by alex-carbonium** [comment]
not sure what is wrong, can you add some comments

**Comment by Boorj** [comment]
On the 1st picture: i dragged object to the left, and white rectangle shifted right.
That was, probably, because of relative coordinates to group bounding box.

**Comment by defr0zen** [comment]
There were a few problems when adding/removing elements in isolation mode, should be fixed now.
