### ISSUE TITLE
[bug] Undo doesn't work

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#310]
No repro.

This is the case:
- created text
- cloned by alt drag
- edited
- ctrl+C (copied)
- pressed undo

![image](https://user-images.githubusercontent.com/2145313/31551144-e449d8ac-b05d-11e7-8003-1b5f7484ab0b.png)

broken here:
![image](https://user-images.githubusercontent.com/2145313/31551206-0926c9d2-b05e-11e7-98f8-28ec132df249.png)

**Comment by defr0zen** [comment]
Can't repro. This might have been caused by another error before the fatality dialog has been introduced.
