### ISSUE TITLE
[bug] canvas doesn't allow to shrink artboard

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#315]
Not always, so no repro.
![2017-10-14_14-29-06](https://user-images.githubusercontent.com/2145313/31574242-92aac34c-b0f5-11e7-9a2b-ddd54a9908da.gif)

**Comment by alex-carbonium** [comment]
by design, most likely you have anchors on the canvas?

**Comment by Boorj** [comment]
Probably. Can't 100% recall, sorry.
