### ISSUE TITLE
[bug] incorrect ordering, when create artboard underneath objects

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#316]
when you create artboard below objects, objects are rearranged
![2017-10-14_14-37-14](https://user-images.githubusercontent.com/2145313/31574251-bca60e54-b0f5-11e7-91e5-3b5fd31491fe.gif)

**Comment by Boorj** [comment]
also works incorrectly when pasting objects. Sometimes it breaks the original order.

**Comment by defr0zen** [comment]
For pasting need more specific steps
