### ISSUE TITLE
[bug] Layers panel not highlighting objects

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#317]
- create object on pasteboard, when something is selected in artboard. New object won't be indicated.
![2017-10-14_15-42-51](https://user-images.githubusercontent.com/2145313/31574301-e6ca096e-b0f6-11e7-9690-fda05b6a654d.gif)
_also here you can see unexpected scroll - is it a bug?_
- sometimes when you clone objects by `alt+drag` - new objects are selected in designer, but not in layers panel (as seen in  #316 )

**Comment by defr0zen** [comment]
@Boorj Unexpected scroll is by design :) When you press back in layers, all artboards are fit on screen. Double clicking artboard icon fits selected artboard (this probably has to be improved somehow.)

**Comment by defr0zen** [comment]
The rest has been fixed as part of other commits.
