### ISSUE TITLE
[bug] line 0-height fatality

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#320]
![2017-10-14_20-06-25](https://user-images.githubusercontent.com/2145313/31575942-3673bb94-b11b-11e7-99f0-1f79e14e6148.gif)

**Comment by defr0zen** [comment]
Assigning since you have more context about how lines work

**Comment by Boorj** [comment]
also relates to #340

**Comment by alex-carbonium** [comment]
fixed
