### ISSUE TITLE
[bug] unwanted selection inside group

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#321]
I have a group. When i click on object inside that group - it's being selected, instead of selecting whole group.
![2017-10-14_20-13-47](https://user-images.githubusercontent.com/2145313/31575987-67f0353e-b11c-11e7-9775-e9c2bf2d080e.gif)

**Comment by defr0zen** [comment]
The cursor is white so you have direct selection enabled, therefore you select inside groups. Press "v" for regular selection tool.
