### ISSUE TITLE
[fix] hard to select line

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#340]
When you hover line - middle spine line appears. When you click on line - it doesn't give a result.
In this video i am **constantly clicking** while moving mouse:

![2017-10-18_01-39-36](https://user-images.githubusercontent.com/2145313/31683011-dda3212a-b3a5-11e7-8594-a54e7bddaab9.gif)
Clicking on line pixels doesn't help. Only in some defined areas.

**Comment by defr0zen** [comment]
Assigning since you have more context about how lines work

**Comment by Boorj** [comment]
1
---
also there's a problem with spine line. Sometimes it's in the middle of line (when hover), nodes are on the corner of line (if line is a rectangle with 1px height).
And clickable area is.. i don't know where.


2
---

@alex-carbonium **very** common situation, when you need to resize *only* width.  
Can you make this in easier way, except selecting one node and moving that with shift? You should accept that mouse target area for this operation [Fitt's law](https://en.wikipedia.org/wiki/Fitts's_law) should be bigger.

So could you make a border for line with some outer offset? 

![image](https://user-images.githubusercontent.com/2145313/31850421-8275a380-b67b-11e7-9041-30d5f4bf946d.png)

- 2 dots for vertical or horizontal lines
- 4 dots for diagonal lines

**Comment by Boorj** [comment]
#### please don't forget
that clickable area for the 1st case (aligned lines === vert / horiz) should be big enough on any **zoom level**.
When it's a big zoom level - you can increase clickable area
![image](https://user-images.githubusercontent.com/2145313/31850518-6b79e36a-b67d-11e7-8da1-2c5a32eafc39.png)

**Comment by alex-carbonium** [comment]
fixed only clickable area for line

**Comment by Boorj** [comment]
@defr0zen @alex-carbonium - what do you think about the other suggestion? Should i take it to another issue (feature request) ?
