### ISSUE TITLE
[bug] Disallow constraints

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#354]
#### disable
I suppose, constraints shouldn't be active in situations, when it's out of place / unused.
You could just disable it in settings. Probably, show, but make "disabled" / grey.

#### disallow in groups
I understand that constraints are quite useful in some situations. But i suggest **disallow setting constraints ** in groups and and aligning in groups.
For example, you could add 'smartbox' or whatever, so all aligning/responsive features will be isolated for canvas/stack/special group containers.

**Comment by defr0zen** [comment]
There are no constraints in groups, not sure if it makes sense to grey out in properties - it will take lots of space for no reason.

**Comment by Boorj** [comment]
then you can just hide that properties. @defr0zen  what do you think? if element's parent is not a container, can you hide constraint props? they are unused. And only confusing

**Comment by defr0zen** [comment]
Constraints are already hidden if the parent does not respect them. In what case did you see them visible?

**Comment by Boorj** [comment]
inside groups!
![image](https://user-images.githubusercontent.com/2145313/31859911-9ec71480-b73c-11e7-8457-2f645d366eaf.png)

**Comment by Boorj** [comment]
@defr0zen interesting fact, if you directly select the object, constraints are hidden:

![image](https://user-images.githubusercontent.com/2145313/31859924-cf9fc002-b73c-11e7-92b4-315c3f2f1c58.png)

So i suppose, **it's a bug**
