### ISSUE TITLE
[bug] incorrect artboard detection

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#360]
- uploaded big image (with 3 screens)
- cropped image to 1 artboard size
- copied to another artboard
- moved image content inside copied image frame
![2017-10-21_20-23-13](https://user-images.githubusercontent.com/2145313/31852195-b8f46596-b69d-11e7-9e63-068532ede948.gif)

**Comment by defr0zen** [comment]
@Boorj what do you mean by 
> moved image content inside copied image frame

?

**Comment by Boorj** [comment]
i have:
image frame >  image content.  So i moved **image content** inside copied **image frame**

**Comment by defr0zen** [comment]
Made several related fixes, considering this closed.
