### ISSUE TITLE
Drop image to rectangle doesn't work

### ISSUE THREAD

**Issue by alex-carbonium** [CarbonDesigns/carbon-ui#38]
It works to drop to circle, but for rect the image is not visible

**Comment by defr0zen** [comment]
We should improve the "use as mask feature":
- Hide the property
- Maybe create the new special container which accepts a single element. When a new element is dropped, the element must be replaced. 
- In the layers, the new container should show mask -> element, for example Circle -> Image.

**Comment by defr0zen** [comment]
Fixed
