### ISSUE TITLE
Selected elements on stateboards are shown on top

### ISSUE THREAD

**Issue by defr0zen** [CarbonDesigns/carbon-ui#404]
http://dev.carbonium.io/q/JJVT7r

There is a text beneath the green rect, but it goes behind when the rect is selected.
Happens only on stateboards, but consistently.

![image](https://user-images.githubusercontent.com/27830024/32922293-c55ea12c-cb31-11e7-9957-6225a4f4d5c8.png)

**Comment by defr0zen** [comment]
Still reproes in the same project. Just keep selecting blue and green rectangles one after another.

**Comment by alex-carbonium** [comment]
hm, can't repro
