### ISSUE TITLE
Path operations menu

### ISSUE THREAD

**Issue by alex-carbonium** [CarbonDesigns/carbon-ui#470]
![image](https://user-images.githubusercontent.com/29034418/37085290-f780501e-21f4-11e8-8d27-fdbb1990f242.png)

**Comment by denizkurtcepe** [comment]
<img width="255" alt="screen shot 2018-05-09 at 02 09 56" src="https://user-images.githubusercontent.com/35198298/39789100-2188f66c-532e-11e8-8849-f22fa3fd6ccf.png">

**Comment by alex-carbonium** [comment]
good
