### ISSUE TITLE
SignUp button for not logged in user

### ISSUE THREAD

**Issue by alex-carbonium** [CarbonDesigns/carbon-ui#473]
When user open an app for the first time he is not logged-in yet, we need to show quite vissible sign up button in the header, i.e. like this
![image](https://user-images.githubusercontent.com/29034418/37117715-45da4910-2252-11e8-83bf-0aa411be6acf.png)

**Comment by denizkurtcepe** [comment]
<img width="799" alt="screen shot 2018-05-09 at 01 53 14" src="https://user-images.githubusercontent.com/35198298/39788662-c3ab16c6-532b-11e8-993c-72b163704065.png">

**Comment by denizkurtcepe** [comment]
Log in Or Sign Up. it's up to you,

**Comment by alex-carbonium** [comment]
good
