### ISSUE TITLE
Missing tool icons

### ISSUE THREAD

**Issue by alex-carbonium** [CarbonDesigns/carbon-ui#477]
- [ ] hand tool
- [x] artboard tool
- [ ] artobard viewer tool
- [x] polygon tool
- [x] triangle tool
- [x] direct selection tool

**Comment by denizkurtcepe** [comment]
<img width="425" alt="screen shot 2018-05-09 at 01 47 58" src="https://user-images.githubusercontent.com/35198298/39788504-0406a006-532b-11e8-842a-97ca46f5eda5.png">

**Comment by alex-carbonium** [comment]
good
