### ISSUE TITLE
Add current project name to the header of the app

### ISSUE THREAD

**Issue by alex-carbonium** [CarbonDesigns/carbon-ui#478]
I think, it make a lot of sense to show project name in the header of the app.
Sometimes users have several similar projects, so we need an easy way to understand the context for the users.

**Comment by denizkurtcepe** [comment]
![bitmap 2x](https://user-images.githubusercontent.com/35198298/39178839-fb609750-47b2-11e8-82ea-f7e52a4e015c.png)

**Comment by denizkurtcepe** [comment]
what do you think ?

**Comment by alex-carbonium** [comment]
looks good
