### ISSUE TITLE
Design zoom menu to keep functionality

### ISSUE THREAD

**Issue by alex-carbonium** [CarbonDesigns/carbon-ui#479]
![image](https://user-images.githubusercontent.com/29034418/37347791-ea206688-26d2-11e8-84a3-fe6bc3a39727.png)

**Comment by alex-carbonium** [comment]
Currently we have some features in the zoom menu, I would like to keep functionality as is, but need to update design

**Comment by denizkurtcepe** [comment]
can you share the bigger screenshot with me?

**Comment by alex-carbonium** [comment]
![image](https://user-images.githubusercontent.com/29034418/38173140-2c1e2e2c-35b9-11e8-93b3-4969521f42fc.png)
