### ISSUE TITLE
constraint property editor

### ISSUE THREAD

**Issue by alex-carbonium** [CarbonDesigns/carbon-ui#482]
Need a design for the constraints property
![image](https://user-images.githubusercontent.com/29034418/38173165-7ec440f8-35b9-11e8-8a77-ba3edea9ee02.png)

**Comment by denizkurtcepe** [comment]
I will share sketch file.

<img width="285" alt="screen shot 2018-04-05 at 22 45 44" src="https://user-images.githubusercontent.com/35198298/38390950-1cae7218-3923-11e8-8efa-df918ad7eac7.png">
