### ISSUE TITLE
Stroke properties design

### ISSUE THREAD

**Issue by alex-carbonium** [CarbonDesigns/carbon-ui#483]
Need a design for the stroke properties:
![image](https://user-images.githubusercontent.com/29034418/38173173-aa9006ea-35b9-11e8-98e7-4f76f9dc4d99.png)

**Comment by denizkurtcepe** [comment]
I made this before, Do you want me to change these?
You will find in Sketch file.

<img width="284" alt="screen shot 2018-04-05 at 22 42 54" src="https://user-images.githubusercontent.com/35198298/38390841-cc81a0ee-3922-11e8-93cb-03deea7e899a.png">
<img width="297" alt="screen shot 2018-04-05 at 22 43 03" src="https://user-images.githubusercontent.com/35198298/38390842-cca8511c-3922-11e8-8c06-6778f799f229.png">
