### ISSUE TITLE
need design for two more properties for the text control

### ISSUE THREAD

**Issue by alex-carbonium** [CarbonDesigns/carbon-ui#490]
![image](https://user-images.githubusercontent.com/29034418/39672466-da653750-512a-11e8-9ccc-76ff46053492.png)

1. Is the text type, block or label
2. Text decorations (italic, underline, dotted and dashed underline)

**Comment by denizkurtcepe** [comment]
<img width="259" alt="screen shot 2018-05-09 at 23 38 48" src="https://user-images.githubusercontent.com/35198298/39841169-307d4c22-53e2-11e8-8385-3e3a9637d7ed.png">

**Comment by alex-carbonium** [comment]
looks good
