### ISSUE TITLE
how to delete shadow?

### ISSUE THREAD

**Issue by alex-carbonium** [CarbonDesigns/carbon-ui#491]
In the current design how do I delete a shadow?
![image](https://user-images.githubusercontent.com/29034418/39692503-503b2104-51e1-11e8-930f-cd413ddd9da8.png)

**Comment by denizkurtcepe** [comment]
<img width="673" alt="screen shot 2018-05-09 at 01 46 35" src="https://user-images.githubusercontent.com/35198298/39788446-d66835ce-532a-11e8-8461-00b4f7f53a62.png">

**Comment by alex-carbonium** [comment]
good
