### ISSUE TITLE
Path point type icons

### ISSUE THREAD

**Issue by alex-carbonium** [CarbonDesigns/carbon-ui#493]
Missing these icons for the path point:
![image](https://user-images.githubusercontent.com/29034418/39705633-43c4ba6a-520f-11e8-842c-25830a4ef4c3.png)

This is the picture from sketch

**Comment by denizkurtcepe** [comment]
<img width="548" alt="screen shot 2018-05-07 at 21 50 15" src="https://user-images.githubusercontent.com/35198298/39721753-c7c5d5f2-5240-11e8-8563-1a24c1d2d0f2.png">

**Comment by alex-carbonium** [comment]
good
