### ISSUE TITLE
Path tool is imprecise

### ISSUE THREAD

**Issue by defr0zen** [CarbonDesigns/carbon-ui#503]
Few problems on a screen below:
- The _Point rounding_ is set to _Round to half pixels_, but these are way not "half"
- The red dot is where a mouse pointer is, but the new path segment is off.

![image](https://user-images.githubusercontent.com/27830024/44251116-7fec8080-a1f7-11e8-9d9a-5e6dae59f6c8.png)

**Comment by alex-carbonium** [comment]
fixed
