### ISSUE TITLE
Wrong artboard picked up in preview

### ISSUE THREAD

**Issue by defr0zen** [CarbonDesigns/carbon-ui#507]
I have Artboard8 and Artboard10 as shown below
![image](https://user-images.githubusercontent.com/27830024/44446440-1f898480-a5e5-11e8-8b28-7a305114c65f.png)

In preview, it says Artboard8, but shows Artboard10...
![image](https://user-images.githubusercontent.com/27830024/44446417-0c76b480-a5e5-11e8-96d6-ff9ed4666e0f.png)

Changing artboard in dropdown does not help, no errors in console.

**Comment by alex-carbonium** [comment]
fixed
