### ISSUE TITLE
No resize points for quite big rect

### ISSUE THREAD

**Issue by defr0zen** [CarbonDesigns/carbon-ui#89]
![jul-08-2017 23-41-28](https://user-images.githubusercontent.com/27830024/27988941-07189328-6437-11e7-8436-d5d9a8c8afda.gif)

**Comment by defr0zen** [comment]
Still the points are removed too early. Here is a real design below. In sketch and other apps horizontal resize points are drawn.
 
![image](https://user-images.githubusercontent.com/27830024/28944529-2364f5d2-78a3-11e7-8c92-4b092482f27a.png)

**Comment by alex-carbonium** [comment]
fixed
