### ISSUE TITLE
ContextBar should show disabled actions in active group

### ISSUE THREAD

**Issue by defr0zen** [CarbonDesigns/carbon-ui#9]
If at least one action in the group is visible, all other actions should be shown as disabled, instead of being hidden.
This will improve discoverability of available actions.

**Comment by alex-carbonium** [comment]
Not sure about this one. The context can be quite different for different elements, so it doesn't make sence in general to show hidden items. Can you give an example of a item which has to be visible?

**Comment by defr0zen** [comment]
Symbols group has new actions to mark an inner element as text or background.
The actions are enabled only when you are on the element in a master symbol artboard. It's hard to discover these options if you don't see them disabled initially.
